/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sensorNet;

import java.awt.Dialog;
import sensorData.*;

/**
 *
 * @author Mike
 */
public class MainFrame extends javax.swing.JFrame {

    private DatabaseFunctions database = null;
    private Location_crud locationAdminDataView = null;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        database = DatabaseFunctions.getInstance();
        locationAdminDataView = new Location_crud(this, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpenDatabase = new javax.swing.JButton();
        btnCloseDatabase = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jExitMenuItem = new javax.swing.JMenuItem();
        jAdminMenu = new javax.swing.JMenu();
        jRoomMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOpenDatabase.setText("Open Database");
        btnOpenDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDatabaseActionPerformed(evt);
            }
        });

        btnCloseDatabase.setText("Close Database");
        btnCloseDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseDatabaseActionPerformed(evt);
            }
        });

        jFileMenu.setText("File");

        jExitMenuItem.setText("Exit");
        jExitMenuItem.setToolTipText("Exit the application");
        jFileMenu.add(jExitMenuItem);

        jMenuBar1.add(jFileMenu);

        jAdminMenu.setText("Admin");

        jRoomMenuItem.setText("Rooms");
        jRoomMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoomMenuItemActionPerformed(evt);
            }
        });
        jAdminMenu.add(jRoomMenuItem);

        jMenuBar1.add(jAdminMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnOpenDatabase)
                .addGap(46, 46, 46)
                .addComponent(btnCloseDatabase)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenDatabase)
                    .addComponent(btnCloseDatabase))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDatabaseActionPerformed
        
        if (database != null)
            database.openDatabase();
    }//GEN-LAST:event_btnOpenDatabaseActionPerformed

    private void btnCloseDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseDatabaseActionPerformed
        
        if (database != null)
            database.shutDownDatabase();
    }//GEN-LAST:event_btnCloseDatabaseActionPerformed

    private void jRoomMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoomMenuItemActionPerformed
        // open up a new dialog to list all the existing rooms/locations
        // then able to add, edit. delete records
        
        locationAdminDataView.setModalityType(Dialog.ModalityType.DOCUMENT_MODAL);
        locationAdminDataView.setTitle("Room Database");
        locationAdminDataView.setVisible(true);
    }//GEN-LAST:event_jRoomMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseDatabase;
    private javax.swing.JButton btnOpenDatabase;
    private javax.swing.JMenu jAdminMenu;
    private javax.swing.JMenuItem jExitMenuItem;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jRoomMenuItem;
    // End of variables declaration//GEN-END:variables
}
